#!/bin/sh
alias ka="killall" \
	mkd="mkdir -pv" \
	g="git" \
	gua="git remote | xargs -L1 git push --all" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
	src="source venv/bin/activate" \
	dev=". ~/.config/scripts/listprojects.sh" \
	ll="ls -al" \
	h="cd ~/ && ls -a" \
	d="cd ~/Documents && ls -a" \
	D="cd ~/Downloads && ls -a" \
	m="cd ~/Music && ls -a" \
	pp="cd ~/Pictures && ls -a" \
	vv="cd ~/Videos && ls -a" \
	cf="cd ~/.config && ls -a" \
	sc="cd ~/.local/bin && ls -a" \
	mn="cd /mnt && ls -a" \
	cfa="$EDITOR ~/.config/aliasrc" \
	cfz="$EDITOR ~/.zshrc" \
	cfk="$EDITOR ~/.config/skhd/skhdrc" \
