#!/bin/sh
alias ka="killall" \
	mkd="mkdir -pv" \
	g="git" \
	gua="git remote | xargs -L1 git push --all" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ref="source ~/.config/aliasrc" \
	src="source venv/bin/activate" \
	dev=". ~/.local/bin/tools/listprojects" \
	ll="ls -al" \
	h="cd ~/ && ls -a" \
	d="cd ~/Documents && ls -a" \
	D="cd ~/Downloads && ls -a" \
	m="cd ~/Music && ls -a" \
	pp="cd ~/Pictures && ls -a" \
	vv="cd ~/Videos && ls -a" \
	cf="cd ~/.config && ls -a" \
	sc="cd ~/.local/bin && ls -a" \
	mn="cd /mnt && ls -a" \
	cfa="vim ~/.config/aliasrc" \
	cfz="vim ~/.zshrc" \
	cfk="vim ~/.config/skhd/skhdrc" \
	cfk="vim ~/.config/yabai/yabairc" \

# GIT aliases
alias gs="git status"
alias gp='git pull'
alias cg='cd `git rev-parse --show-toplevel`' # Go to top level in git project directory
alias ga="git add"
alias gc="git commit -m"
alias gb="git branch"
alias gpu="git push"
alias gsync="git pull origin develop"
alias gl='git log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset" --abbrev-commit'


# Stop after sending count ECHO_REQUEST packets #
alias ping='ping -c 5'
